--count: 10450709
--count without unkown time survival: 10330832
SELECT
    PUBCSNUM AS PATIENT_ID,

    FIRSTPRM AS FIRST_MALIGN_TUMOR,
    CHEMO_RX_REC AS CHEMOTHERAPY,
    TYPE_TUMOR,
    /*
    CASE WHEN REG = 1501 THEN 1 ELSE 0 END AS STATE_SAN_FRANCISCO_OAKLAND,
    CASE WHEN REG = 1502 THEN 1 ELSE 0 END AS STATE_CONNECTICUT,
    CASE WHEN REG = 1520 THEN 1 ELSE 0 END AS STATE_METROPOLITAN_DETROIT,
    CASE WHEN REG = 1521 THEN 1 ELSE 0 END AS STATE_HAWAII,
    CASE WHEN REG = 1522 THEN 1 ELSE 0 END AS STATE_IOWA,
    CASE WHEN REG = 1523 THEN 1 ELSE 0 END AS STATE_NEW_MEXICO,
    CASE WHEN REG = 1525 THEN 1 ELSE 0 END AS STATE_SEATTLE,
    CASE WHEN REG = 1526 THEN 1 ELSE 0 END AS STATE_UTAH,
    CASE WHEN REG = 1527 THEN 1 ELSE 0 END AS STATE_METROPOLITAN_ATLANTA,
    CASE WHEN REG = 1529 THEN 1 ELSE 0 END AS STATE_ALASKA,
    CASE WHEN REG = 1531 THEN 1 ELSE 0 END AS STATE_SAN_JOSE_MONTEREY,
    CASE WHEN REG = 1535 THEN 1 ELSE 0 END AS STATE_LOS_ANGELES,
    CASE WHEN REG = 1537 THEN 1 ELSE 0 END AS STATE_RURAL_GEORGIA,
    CASE WHEN REG = 1541 THEN 1 ELSE 0 END AS STATE_GREATER_CALIFORNIA,
    CASE WHEN REG = 1542 THEN 1 ELSE 0 END AS STATE_KENTUCKY,
    CASE WHEN REG = 1543 THEN 1 ELSE 0 END AS STATE_LOUISIANA,
    CASE WHEN REG = 1544 THEN 1 ELSE 0 END AS STATE_NEW_JERSEY,
    CASE WHEN REG = 1547 THEN 1 ELSE 0 END AS STATE_GREATER_GEORGIA,
    */
    CASE WHEN MAR_STAT = 1 THEN 1 ELSE 0 END AS MARITAL_STATUS_SINGLE,
    CASE WHEN MAR_STAT = 2 THEN 1 ELSE 0 END AS MARITAL_STATUS_MARRIED,
    CASE WHEN MAR_STAT = 3 THEN 1 ELSE 0 END AS MARITAL_STATUS_SEPARATED,

    CASE WHEN MAR_STAT = 4 THEN 1 ELSE 0 END AS MARITAL_STATUS_DIVORCED,

    CASE WHEN MAR_STAT = 5 THEN 1 ELSE 0 END AS MARITAL_STATUS_WIDOWED,
    CASE
        WHEN MAR_STAT = 6 THEN 1 ELSE 0
    END AS MARITAL_STATUS_UNMARRIED_OR_DOMESTIC_PARTNER,

    -- http://www.fosp.saude.sp.gov.br/fosp/diretoria-adjunta-de-informacao-e-epidemiologia/cid-o/
    CASE WHEN SEX = 2 THEN 1 ELSE 0 END AS SEX_FEMALE,
    CASE WHEN COALESCE(
        CASE WHEN SEQ_NUM < 60 THEN GREATEST(SEQ_NUM - 1, 0)
            WHEN SEQ_NUM = 99 THEN 0 END,
        0) > 0 THEN 1 ELSE 0 END AS PREVIOUS_TUMOR_MALIGN,
    CASE WHEN COALESCE(
        CASE WHEN SEQ_NUM >= 60 THEN GREATEST(SEQ_NUM - 61, 0)
            WHEN SEQ_NUM = 88 THEN 0 END,
        0) > 0 THEN 1 ELSE 0 END AS PREVIOUS_TUMOR_BENIGN,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C00' THEN 1 ELSE 0
    END AS ICD_LIP,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C01' THEN 1 ELSE 0
    END AS ICD_TONGUE_BASE,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C02' THEN 1 ELSE 0
    END AS ICD_TONGUE_OTHER,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C03' THEN 1 ELSE 0
    END AS ICD_GUM,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C04' THEN 1 ELSE 0
    END AS ICD_MOUTH_FLOOR,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C05' THEN 1 ELSE 0
    END AS ICD_PALATE,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C06' THEN 1 ELSE 0
    END AS ICD_MOUTH_OTHER,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C07' THEN 1 ELSE 0
    END AS ICD_PAROTID_GLAND,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C08' THEN 1 ELSE 0
    END AS ICD_SALIVARY_GLANDS_OTHER,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C09' THEN 1 ELSE 0
    END AS ICD_AMYGDALA,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C10' THEN 1 ELSE 0
    END AS ICD_OROPHARYNX,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C11' THEN 1 ELSE 0
    END AS ICD_NASOPHARYNX,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C12' THEN 1 ELSE 0
    END AS ICD_PIRIFORM_SINUS,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C13' THEN 1 ELSE 0
    END AS ICD_HYPOPHARYNX,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C14' THEN 1 ELSE 0
    END AS ICD_LIP_ORAL_CAVITY_AND_PHARYNX_OTHER,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C15' THEN 1 ELSE 0
    END AS ICD_ESOPHAGUS,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C16' THEN 1 ELSE 0
    END AS ICD_STOMACH,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C17' THEN 1 ELSE 0
    END AS ICD_SMALL_INTESTINE,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C18' THEN 1 ELSE 0
    END AS ICD_COLON,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C19' THEN 1 ELSE 0
    END AS ICD_RECTOSIGMOID_JUNCTION,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C20' THEN 1 ELSE 0
    END AS ICD_RECTUM,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C21' THEN 1 ELSE 0
    END AS ICD_ANUS,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C22' THEN 1 ELSE 0
    END AS ICD_LIVER_BILE_DUCTS,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C23' THEN 1 ELSE 0
    END AS ICD_GALLBLADDER,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C24' THEN 1 ELSE 0
    END AS ICD_BILE_DUCTS_OTHER,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C25' THEN 1 ELSE 0
    END AS ICD_PANCREAS,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C26' THEN 1 ELSE 0
    END AS ICD_DIGESTIVE_SYSTEM_OTHER,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C30' THEN 1 ELSE 0
    END AS ICD_NASAL_CAVITY_AND_MIDDLE_EAR,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C31' THEN 1 ELSE 0
    END AS ICD_SINUSES,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C32' THEN 1 ELSE 0
    END AS ICD_LARYNX,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C33' THEN 1 ELSE 0
    END AS ICD_TRACHEA,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C34' THEN 1 ELSE 0
    END AS ICD_BRONCHI_AND_LUNGS,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C37' THEN 1 ELSE 0
    END AS ICD_THYMUS,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C38' THEN 1 ELSE 0
    END AS ICD_HEART_MEDIASTINUM_AND_PLEURA,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C39' THEN 1 ELSE 0
    END AS ICD_RESPIRATORY_SYSTEM_AND_INTRATHORACIC_ORGANS_OTHER,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C40' THEN 1 ELSE 0
    END AS ICD_BONES_AND_JOINT_CARTILAGES_LIMBS,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C41' THEN 1 ELSE 0
    END AS ICD_BONES_AND_JOINT_CARTILAGES_LIMBS_OTHER,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C42' THEN 1 ELSE 0
    END AS ICD_HEMATOPOIETIC_AND_RETICULOENDOTHELIAL_SYSTEM,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C44' THEN 1 ELSE 0
    END AS ICD_SKIN,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C47' THEN 1 ELSE 0
    END AS ICD_PERIPHERAL_NERVES_AND_AUTONOMIC_NERVOUS_SYSTEM,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C48' THEN 1 ELSE 0
    END AS ICD_RETROPERITONEUM_AND_PERITONEUM,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C49' THEN 1 ELSE 0
    END AS ICD_CONNECTIVE_TISSUE_SUBCUTANEOUS_AND_OTHER_SOFT_TISSUES,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C50' THEN 1 ELSE 0
    END AS ICD_BREAST,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C51' THEN 1 ELSE 0
    END AS ICD_VULVA,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C52' THEN 1 ELSE 0
    END AS ICD_VAGINA,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C53' THEN 1 ELSE 0
    END AS ICD_CERVIX,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C54' THEN 1 ELSE 0
    END AS ICD_UTERUS_BODY,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C55' THEN 1 ELSE 0
    END AS ICD_UTERUS_OTHER,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C56' THEN 1 ELSE 0
    END AS ICD_OVARY,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C57' THEN 1 ELSE 0
    END AS ICD_FEMALE_GENITALS_OTHER,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C58' THEN 1 ELSE 0
    END AS ICD_PLACENTA,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C60' THEN 1 ELSE 0
    END AS ICD_PENIS,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C61' THEN 1 ELSE 0
    END AS ICD_PROSTATE,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C62' THEN 1 ELSE 0
    END AS ICD_TESTICLE,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C63' THEN 1 ELSE 0
    END AS ICD_MALE_GENITALS_OTHER,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C64' THEN 1 ELSE 0
    END AS ICD_KIDNEY,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C65' THEN 1 ELSE 0
    END AS ICD_RENAL_PELVIS,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C66' THEN 1 ELSE 0
    END AS ICD_URETER,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C67' THEN 1 ELSE 0
    END AS ICD_BLADDER,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C68' THEN 1 ELSE 0
    END AS ICD_URINARY_SYSTEM_OTHER,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C69' THEN 1 ELSE 0
    END AS ICD_EYE_AND_ATTACHMENTS,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C70' THEN 1 ELSE 0
    END AS ICD_MENINGES,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C71' THEN 1 ELSE 0
    END AS ICD_BRAIN,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C72' THEN 1 ELSE 0
    END AS ICD_SPINAL_CORD_CRANIAL_NERVES_AND_OTHER_PARTS_AUTONOMIC_NERVOUS_SYSTEM,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C73' THEN 1 ELSE 0
    END AS ICD_THYROID_GLAND,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C74' THEN 1 ELSE 0
    END AS ICD_ADRENAL_GLAND,

    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C75' THEN 1 ELSE 0
    END AS ICD_ENDOCRINE_GLANDS_OTHER,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C76' THEN 1 ELSE 0
    END AS ICD_LOCATION_OTHER,
    CASE
        WHEN SUBSTRING(PRIMSITE, 0, 3) = 'C77' THEN 1 ELSE 0
    END AS ICD_LYMPH_NODES,
    CASE WHEN LATERAL_ = 1 THEN 1 ELSE 0 END AS LATERALITY_RIGHT,
    CASE WHEN LATERAL_ = 2 THEN 1 ELSE 0 END AS LATERALITY_LEFT,

    CASE
        WHEN LATERAL_ IN (1, 2, 3) THEN 1 ELSE 0
    END AS LATERALITY_ONE_SIDE_INVOLVED,
    CASE WHEN LATERAL_ = 4 THEN 1 ELSE 0 END AS LATERALITY_BILATERAL,
    CASE WHEN LATERAL_ = 5 THEN 1 ELSE 0 END AS LATERALITY_MIDLINE,
    CASE WHEN BEHO3V = 0 THEN 1 ELSE 0 END AS BEHAVIOR_BENIGN,

    CASE WHEN BEHO3V = 1 THEN 1 ELSE 0 END AS BEHAVIOR_MALIGNANT_POTENTIAL,
    CASE
        WHEN BEHO3V = 2 THEN 1 ELSE 0
    END AS BEHAVIOR_CARCIONA_IN_SITU_INTRAEPITHELIAL_NONINFILTRATING_NONINVASIVE,
    CASE WHEN BEHO3V = 3 THEN 1 ELSE 0 END AS BEHAVIOR_MALIGNANT,
    CASE WHEN GRADE = 1 THEN 1 ELSE 0 END AS GRADE_ONE,
    CASE WHEN GRADE = 2 THEN 1 ELSE 0 END AS GRADE_TWO,
    CASE WHEN GRADE = 3 THEN 1 ELSE 0 END AS GRADE_THREE,
    CASE WHEN GRADE = 4 THEN 1 ELSE 0 END AS GRADE_FOUR,
    CASE WHEN GRADE = 5 THEN 1 ELSE 0 END AS GRADE_T_CELL,

    CASE WHEN GRADE = 6 THEN 1 ELSE 0 END AS GRADE_B_CELL,
    CASE WHEN GRADE = 7 THEN 1 ELSE 0 END AS GRADE_NULL_CELL,
    CASE WHEN GRADE = 8 THEN 1 ELSE 0 END AS GRADE_NK_CELL,
    CASE
        WHEN
            CSTUMSIZ BETWEEN 0 AND 99 OR CSTUMSIZ IN (
                990, 991, 992, 993, 994, 995, 888
            ) OR TUMSIZS BETWEEN 0 AND 99 OR TUMSIZS IN (990) THEN 1
        ELSE 0
    END AS TUMOR_SIZE_000_099_MILLIMETERS,
    CASE
        WHEN
            CSTUMSIZ BETWEEN 100 AND 199 OR TUMSIZS BETWEEN 100 AND 199 THEN 1
        ELSE 0
    END AS TUMOR_SIZE_100_199_MILLIMETERS,
    CASE
        WHEN
            CSTUMSIZ BETWEEN 200 AND 299 OR TUMSIZS BETWEEN 200 AND 299 THEN 1
        ELSE 0
    END AS TUMOR_SIZE_200_299_MILLIMETERS,
    CASE
        WHEN
            CSTUMSIZ BETWEEN 300 AND 399 OR TUMSIZS BETWEEN 300 AND 399 THEN 1
        ELSE 0
    END AS TUMOR_SIZE_300_399_MILLIMETERS,
    CASE
        WHEN
            CSTUMSIZ BETWEEN 400 AND 499 OR TUMSIZS BETWEEN 400 AND 499 THEN 1
        ELSE 0
    END AS TUMOR_SIZE_400_499_MILLIMETERS,
    CASE
        WHEN
            CSTUMSIZ BETWEEN 500 AND 599 OR TUMSIZS BETWEEN 500 AND 599 THEN 1
        ELSE 0
    END AS TUMOR_SIZE_500_599_MILLIMETERS,
    CASE
        WHEN
            CSTUMSIZ BETWEEN 600 AND 699 OR TUMSIZS BETWEEN 600 AND 699 THEN 1
        ELSE 0
    END AS TUMOR_SIZE_600_699_MILLIMETERS,
    CASE
        WHEN
            CSTUMSIZ BETWEEN 700 AND 799 OR TUMSIZS BETWEEN 700 AND 799 THEN 1
        ELSE 0
    END AS TUMOR_SIZE_700_799_MILLIMETERS,

    CASE
        WHEN
            CSTUMSIZ BETWEEN 800 AND 899 OR TUMSIZS BETWEEN 800 AND 899 THEN 1
        ELSE 0
    END AS TUMOR_SIZE_800_899_MILLIMETERS,


    CASE
        WHEN
            CSTUMSIZ BETWEEN 900 AND 989 OR TUMSIZS BETWEEN 900 AND 989 THEN 1
        ELSE 0
    END AS TUMOR_SIZE_900_MORE_MILLIMETERS,

    CASE WHEN SUBSTRING(DASRCT, 2, 1) = '0' THEN 'T0'
        WHEN SUBSTRING(DASRCT, 2, 1) = 'A' THEN 'Ta'
        WHEN SUBSTRING(DASRCT, 2, 1) = 'I' THEN 'Tis'
        WHEN SUBSTRING(DASRCT, 2, 1) = '1' THEN 'T1'
        WHEN SUBSTRING(DASRCT, 2, 1) = '2' THEN 'T2'
        WHEN SUBSTRING(DASRCT, 2, 1) = '3' THEN 'T3'
        WHEN SUBSTRING(DASRCT, 2, 1) = '4' THEN 'T4' END AS TUMOR_STAGING_T_2016_MORE,
    CASE WHEN ADJTM_6VALUE IN (0) THEN 'T0'
        WHEN ADJTM_6VALUE IN (1) THEN 'Ta'
        WHEN ADJTM_6VALUE IN (5, 6, 7) THEN 'Tis'
        WHEN
            ADJTM_6VALUE IN (
                10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 80, 81
            ) THEN 'T1'
        WHEN ADJTM_6VALUE IN (20, 21, 22, 23, 29) THEN 'T2'
        WHEN ADJTM_6VALUE IN (30, 31, 32, 33, 39) THEN 'T3'
        WHEN ADJTM_6VALUE IN (40, 41, 42, 43, 44, 49) THEN 'T4' END AS TUMOR_STAGING_T_1988_2015_BREAST,
    CASE WHEN DAJCC7T IN (0) THEN 'T0'
        WHEN DAJCC7T IN (10) THEN 'Ta'
        WHEN DAJCC7T IN (50, 60, 70) THEN 'Tis'
        WHEN
            DAJCC7T IN (
                100, 110, 120, 130, 140, 150, 160, 170, 180, 181, 199, 800, 810
            ) THEN 'T1'
        WHEN DAJCC7T IN (200, 210, 211, 212, 213, 220, 230, 240, 299) THEN 'T2'
        WHEN DAJCC7T IN (300, 310, 320, 330, 399) THEN 'T3'
        WHEN DAJCC7T IN (400, 410, 420, 430, 440, 450, 499) THEN 'T4' END AS TUMOR_STAGING_T_2010_2015_7_ED,
    CASE WHEN DAJCCT IN (0) THEN 'T0'
        WHEN DAJCCT IN (1) THEN 'Ta'
        WHEN DAJCCT IN (5, 6, 7) THEN 'Tis'
        WHEN
            DAJCCT IN (10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 80, 81) THEN 'T1'
        WHEN DAJCCT IN (20, 21, 22, 23, 29) THEN 'T2'
        WHEN DAJCCT IN (30, 31, 32, 33, 39) THEN 'T3'
        WHEN DAJCCT IN (40, 41, 42, 43, 44, 49) THEN 'T4' END AS TUMOR_STAGING_T_2004_2015_6_ED,
    CASE WHEN T_VALUE IN (70, 71, 72) THEN 'T0'
        WHEN T_VALUE IN (1) THEN 'Ta'
        WHEN T_VALUE IN (0) THEN 'Tis'
        WHEN T_VALUE IN (10, 11, 12, 13, 16, 17, 19) THEN 'T1'
        WHEN T_VALUE IN (20, 21, 22, 23, 29) THEN 'T2'
        WHEN T_VALUE IN (30, 31, 32, 33, 39) THEN 'T3'
        WHEN T_VALUE IN (40, 41, 42, 43, 44, 49) THEN 'T4' END AS TUMOR_STAGING_T_1988_2003,

    CASE WHEN DAJCCN IN (0, 1, 2, 3, 4) THEN 'N0'
        WHEN DAJCCN IN (10, 11, 12, 13, 18, 19) THEN 'N1'
        WHEN DAJCCN IN (20, 21, 22, 23, 29) THEN 'N2'
        WHEN DAJCCN IN (30, 31, 32, 33, 39) THEN 'N3' END AS TUMOR_STAGING_N_2004_2015_6_ED,
    CASE WHEN ADJNM_6VALUE IN (0, 1, 2, 3, 4, 9) THEN 'N0'
        WHEN ADJNM_6VALUE IN (10, 11, 12, 13, 18, 19) THEN 'N1'
        WHEN ADJNM_6VALUE IN (20, 21, 22, 23, 29) THEN 'N2'
        WHEN ADJNM_6VALUE IN (30, 31, 32, 33, 39) THEN 'N3' END AS TUMOR_STAGING_N_1988_2015_BREAST,
    CASE WHEN DAJCC7N IN (0, 10, 20, 30, 40) THEN 'N0'
        WHEN DAJCC7N IN (100, 110, 120, 130, 180, 199) THEN 'N1'
        WHEN DAJCC7N IN (200, 210, 220, 230, 299) THEN 'N2'
        WHEN DAJCC7N IN (300, 310, 320, 330, 399) THEN 'N3'
        WHEN DAJCC7N IN (400) THEN 'N4' END AS TUMOR_STAGING_N_2010_2015_7_ED,
    CASE WHEN N_VALUE IN (0) THEN 'N0'
        WHEN N_VALUE IN (10, 11, 12, 19) THEN 'N1'
        WHEN N_VALUE IN (20, 21, 22, 23) THEN 'N2'
        WHEN N_VALUE IN (30) THEN 'N3' END AS TUMOR_STAGING_N_1988_2003,
    CASE WHEN SUBSTRING(DASRCN, 2, 1) = '0' THEN 'N0'
        WHEN SUBSTRING(DASRCN, 2, 1) = '1' THEN 'N1'
        WHEN SUBSTRING(DASRCN, 2, 1) = '2' THEN 'N2'
        WHEN SUBSTRING(DASRCN, 2, 1) = '3' THEN 'N3'
        WHEN SUBSTRING(DASRCN, 2, 1) = '4' THEN 'N4' END AS TUMOR_STAGING_N_2016_MORE,

    CASE WHEN DAJCCM IN (0) THEN 'M0'
        WHEN DAJCCM IN (10, 11, 12, 13, 19) THEN 'M1' END AS TUMOR_STAGING_M_2004_2015_6_ED,
    CASE WHEN ADJM_6VALUE IN (0) THEN 'M0'
        WHEN ADJM_6VALUE IN (10, 11, 12, 13, 19) THEN 'M1' END AS TUMOR_STAGING_M_1988_2015_BREAST,
    CASE WHEN DAJCC7M IN (0, 10) THEN 'M0'
        WHEN DAJCC7M IN (100, 110, 120, 130, 140, 150, 199) THEN 'M1' END AS TUMOR_STAGING_M_2010_2015_7_ED,
    CASE WHEN M_VALUE IN (0) THEN 'M0'
        WHEN M_VALUE IN (10, 11, 12) THEN 'M1' END AS TUMOR_STAGING_M_1988_2003,
    CASE WHEN SUBSTRING(DASRCM, 2, 1) = '0' THEN 'M0'
        WHEN SUBSTRING(DASRCM, 2, 1) = '1' THEN 'M1' END AS TUMOR_STAGING_M_2016_MORE,

    CASE WHEN DAJCCSTG IN (0, 1, 2) THEN '0'
        WHEN
            DAJCCSTG IN (
                10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 23, 24, 20, 21, 22
            ) THEN '1'
        WHEN
            DAJCCSTG IN (
                30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43
            ) THEN '2'
        WHEN
            DAJCCSTG IN (
                50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63
            ) THEN '3'
        WHEN DAJCCSTG IN (70, 71, 72, 73, 74) THEN '4' END AS TUMOR_STAGING_STAGE_2004_2015_6_ED,
    CASE WHEN AJ_3SEER IN (0) THEN '0'
        WHEN AJ_3SEER IN (10, 11, 12, 13, 18, 19) THEN '1'
        WHEN AJ_3SEER IN (20, 21, 22, 23, 29) THEN '2'
        WHEN AJ_3SEER IN (30, 31, 32, 33, 39) THEN '3'
        WHEN AJ_3SEER IN (40, 41, 42, 49) THEN '4' END AS TUMOR_STAGING_STAGE_1988_2003,
    CASE WHEN DAJCC7STG IN (000, 010, 020) THEN '0'
        WHEN
            DAJCC7STG IN (
                100,
                110,
                120,
                130,
                140,
                121,
                150,
                160,
                170,
                151,
                180,
                190,
                230,
                140,
                200,
                210,
                220
            ) THEN '1'
        WHEN
            DAJCC7STG IN (
                300,
                310,
                320,
                321,
                322,
                323,
                330,
                340,
                350,
                360,
                370,
                380,
                390,
                400,
                410,
                420,
                430
            ) THEN '2'
        WHEN
            DAJCC7STG IN (
                500,
                510,
                520,
                530,
                540,
                541,
                542,
                550,
                560,
                570,
                580,
                590,
                600,
                610,
                620,
                630
            ) THEN '3'
        WHEN DAJCC7STG IN (700, 710, 720, 730, 740) THEN '4' END AS TUMOR_STAGING_STAGE_2010_2015_7_ED,
    CASE WHEN ADJAJCCSTG IN (0, 1, 2) THEN '0'
        WHEN
            ADJAJCCSTG IN (
                10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24
            ) THEN '1'
        WHEN
            ADJAJCCSTG IN (
                30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43
            ) THEN '2'
        WHEN
            ADJAJCCSTG IN (
                50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63
            ) THEN '3'
        WHEN ADJAJCCSTG IN (70, 71, 72, 73, 74) THEN '4' END AS TUMOR_STAGING_STAGE_1988_2015_BREAST,
    CASE WHEN SUBSTRING(DSRPSG, 1, 1) = '0' THEN '0'
        WHEN SUBSTRING(DSRPSG, 1, 1) = '1' THEN '1'
        WHEN SUBSTRING(DSRPSG, 1, 1) = '2' THEN '2'
        WHEN SUBSTRING(DSRPSG, 1, 1) = '3' THEN '3'
        WHEN SUBSTRING(DSRPSG, 1, 1) = '4' THEN '4' END AS TUMOR_STAGING_STAGE_2016_MORE,

    CASE WHEN DSS1977S = 0 THEN 'in situ'
        WHEN DSS1977S = 1 THEN 'localized'
        WHEN DSS1977S IN (2, 3, 4, 5) THEN 'regional'
        WHEN DSS1977S = 7 THEN 'distant' END AS TUMOR_EXTENSION_2004_2015_SEER,
    CASE WHEN HST_STGA = 0 THEN 'in situ'
        WHEN HST_STGA IN (1, 8) THEN 'localized'
        WHEN HST_STGA = 2 THEN 'regional'
        WHEN HST_STGA = 4 THEN 'distant' END AS TUMOR_EXTENSION_1973_2015,
    CASE WHEN SSS77VZ = 0 THEN 'in situ'
        WHEN SSS77VZ = 1 THEN 'localized'
        WHEN SSS77VZ IN (2, 3, 4, 5) THEN 'regional'
        WHEN SSS77VZ = 7 THEN 'distant' END AS TUMOR_EXTENSION_2004_2015,
    CASE
        WHEN
            SURGPRIF BETWEEN 10 AND 80 OR SURGPRIF IN (90, 98) THEN 1
        ELSE 0
    END AS SURGERY_PERFORMED,
    CASE
        WHEN
            SURGSCOF IN (1, 2, 3, 4, 5, 6, 7) OR NUMNODES = 98 THEN 1
        ELSE 0
    END AS REGIONAL_LYMPH_NODE_REMOVED,
    CASE
        WHEN SURGSITF IN (1, 2, 3, 4, 5) THEN 1 ELSE 0
    END AS SURGERY_PERFOMERD_NONPRIMARY,
    CASE
        WHEN NO_SURG = 1 THEN 1 ELSE 0
    END AS SURGERY_NOT_PERFORMED_NOT_RECOMMENDED,
    --CASE
    --    WHEN NO_SURG = 2 AND YEAR_DX > 2002 THEN 1 ELSE 0
    --END AS SURGERY_NOT_PERFORMED_OTHER_CONDITIONS,
    CASE
        WHEN NO_SURG = 7 THEN 1 ELSE 0
    END AS SURGERY_NOT_PERFORMED_GUARDIAN_REFUSE,
    CASE WHEN AGE_1REC = 0 THEN 1 ELSE 0 END AS AGE_00,
    CASE WHEN AGE_1REC = 1 THEN 1 ELSE 0 END AS AGE_01_04,
    CASE WHEN AGE_1REC = 2 THEN 1 ELSE 0 END AS AGE_05_09,
    CASE WHEN AGE_1REC = 3 THEN 1 ELSE 0 END AS AGE_10_14,
    CASE WHEN AGE_1REC = 4 THEN 1 ELSE 0 END AS AGE_15_19,
    CASE WHEN AGE_1REC = 5 THEN 1 ELSE 0 END AS AGE_20_24,
    CASE WHEN AGE_1REC = 6 THEN 1 ELSE 0 END AS AGE_25_29,
    CASE WHEN AGE_1REC = 7 THEN 1 ELSE 0 END AS AGE_30_34,
    CASE WHEN AGE_1REC = 8 THEN 1 ELSE 0 END AS AGE_35_39,
    CASE WHEN AGE_1REC = 9 THEN 1 ELSE 0 END AS AGE_40_44,
    CASE WHEN AGE_1REC = 10 THEN 1 ELSE 0 END AS AGE_45_49,
    CASE WHEN AGE_1REC = 11 THEN 1 ELSE 0 END AS AGE_50_54,
    CASE WHEN AGE_1REC = 12 THEN 1 ELSE 0 END AS AGE_55_59,
    CASE WHEN AGE_1REC = 13 THEN 1 ELSE 0 END AS AGE_60_64,
    CASE WHEN AGE_1REC = 14 THEN 1 ELSE 0 END AS AGE_65_69,
    CASE WHEN AGE_1REC = 15 THEN 1 ELSE 0 END AS AGE_70_74,
    CASE WHEN AGE_1REC = 16 THEN 1 ELSE 0 END AS AGE_75_79,
    CASE WHEN AGE_1REC = 17 THEN 1 ELSE 0 END AS AGE_80_84,
    CASE WHEN AGE_1REC = 18 THEN 1 ELSE 0 END AS AGE_85_MORE,
    CASE
        WHEN HISTREC = 0 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_8000_8009_UNSPECIFIED_NEOPLASMS,
    CASE
        WHEN HISTREC = 1 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_8010_8049_EPITHELIAL_NEOPLASMS,
    CASE
        WHEN HISTREC = 2 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_8050_8089_SQUAMOUS_CELL_NEOPLAMS,
    CASE
        WHEN HISTREC = 3 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_8090_8119_BASAL_CELL_NEOPLAMS,
    CASE
        WHEN HISTREC = 4 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_8120_8139_TRANSITIONAL_CELL_PAPILLOMAS_AND_CARCINOMAS,
    CASE
        WHEN HISTREC = 5 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_8140_8389_ADENOMAS_AND_ADENOCARCINOMAS,
    CASE
        WHEN HISTREC = 6 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_8390_8429_ADNEXAL_AND_SKIN_APPENDAGE_NEOPLAMS,
    CASE
        WHEN HISTREC = 7 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_8430_8439_MUCOEPIDERMOID_NEOPLASMS,
    CASE
        WHEN HISTREC = 8 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_8440_8499_CYSTIC_MUCINOUS_AND_SEROUS_NEOPLAMS,
    CASE
        WHEN HISTREC = 9 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_8500_8549_DUCTAL_AND_LOBULAR_NEOPLAMS,
    CASE
        WHEN HISTREC = 10 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_8550_8559_ACINAR_CELL_NEOPLASMS,
    CASE
        WHEN HISTREC = 11 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_8560_8579_COMPLEX_EPITHELIAL_NEOPLAMS,
    CASE
        WHEN HISTREC = 12 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_8580_8589_THYMIC_EPITHELIAL_NEOPLAMS,
    CASE
        WHEN HISTREC = 13 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_8590_8679_SPECIALIZED_GONADAL_NEOPLAMS,
    CASE
        WHEN HISTREC = 14 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_8680_8719_PARAGANGLIOMAS_AND_GLUMUS_TUMORS,
    CASE
        WHEN HISTREC = 15 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_8720_8799_NEVI_AND_MELANOMAS,
    CASE
        WHEN HISTREC = 16 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_8800_8809_SOFT_TISSUE_TUMORS_AND_SARCOMAS,
    CASE
        WHEN HISTREC = 17 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_8810_8839_FIBROMATOUS_NEOPLASMS,
    CASE
        WHEN HISTREC = 18 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_8840_8849_MYXOMATOUS_NEOPLASMS,
    CASE
        WHEN HISTREC = 19 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_8850_8889_LIPOMATOUS_NEOPLASMS,
    CASE
        WHEN HISTREC = 20 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_8890_8929_MYOMATOUS_NEOPLASMS,
    CASE
        WHEN HISTREC = 21 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_8930_8999_COMPLEX_MIXED_AND_STROMAL_NEOPLASMS,
    CASE
        WHEN HISTREC = 22 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9000_9039_FIBROEPITHELIAL_NEOPLASMS,
    CASE
        WHEN HISTREC = 23 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9040_9049_SYNOVIAL_LIKE_NEOPLASMS,
    CASE
        WHEN HISTREC = 24 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9050_9059_MESOTHELIAL_NEOPLASMS,
    CASE
        WHEN HISTREC = 25 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9060_9099_GERM_CELL_NEOPLASMS,
    CASE
        WHEN HISTREC = 26 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9100_9109_TROPHOBLASTIC_NEOPLASMS,
    CASE
        WHEN HISTREC = 27 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9110_9119_MESONEPHROMAS,
    CASE
        WHEN HISTREC = 28 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9120_9169_BLOOD_VESSEL_TUMORS,
    CASE
        WHEN HISTREC = 29 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9170_9179_LYMPHATIC_VESSEL_TUMORS,
    CASE
        WHEN HISTREC = 30 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9180_9249_OSSEOUS_AND_CHONDROMATOUS_NEOPLASMS,
    CASE
        WHEN HISTREC = 31 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9250_9259_GIANT_CELL_TUMORS,
    CASE
        WHEN HISTREC = 32 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9260_9269_MISCELLANEOUS_BONE_TUMORS_C40_C41,
    CASE
        WHEN HISTREC = 33 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9270_9349_ODONTOGENIC_TUMORS_C41,
    CASE
        WHEN HISTREC = 34 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9350_9379_MISCELLANEOUS_TUMORS,
    CASE
        WHEN HISTREC = 35 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9380_9489_GLIOMAS,
    CASE
        WHEN HISTREC = 36 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9490_9529_NEUROEPITHELIOMATOUS_NEOPLASMS,
    CASE
        WHEN HISTREC = 37 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9530_9539_MENINGIOMAS,
    CASE
        WHEN HISTREC = 38 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9540_9579_NERVE_SHEATH_TUMORS,
    CASE
        WHEN HISTREC = 39 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9580_9589_GRANULAR_CELL_TUMORS_ALVEOLAR_SOFT_PART_SARCOMAS,
    CASE
        WHEN HISTREC = 40 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9590_9599_MALIGNANT_LYMPHOMAS,
    CASE
        WHEN HISTREC = 41 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9650_9669_HODGKIN_LYMPHOMAS,
    CASE
        WHEN HISTREC = 42 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9670_9699_NHL_MATURE_B_CELL_LYMPHOMAS,
    CASE
        WHEN HISTREC = 43 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9700_9719_NHL_MATURE_T_AND_NK_CELL_LYMPHOMAS,
    CASE
        WHEN HISTREC = 44 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9720_9729_NHL_PRECURSOR_CELL_LYMPHOBLASTIC_LYMPHOMA,
    CASE
        WHEN HISTREC = 45 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9730_9739_PLASMA_CELL_TUMORS,
    CASE
        WHEN HISTREC = 46 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9740_9749_MAST_CELL_TUMORS,
    CASE
        WHEN HISTREC = 47 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9750_9759_NEOPLASMS_OF_HISTIOCYTES_AND_ACCESSORY_LYMPHOID_CELLS,
    CASE
        WHEN HISTREC = 48 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9760_9769_IMMUNOPROLIFERATIVE_DISEASES,
    CASE
        WHEN HISTREC = 49 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9800_9805_LEUKEMIAS,
    CASE
        WHEN HISTREC = 50 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9820_9839_LYMPHOID_LEUKEMIAS_C421,
    CASE
        WHEN HISTREC = 51 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9840_9939_MYELOID_LEUKEMIAS_C421,
    CASE
        WHEN HISTREC = 52 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9940_9949_OTHER_LEUKEMIAS_C421,
    CASE
        WHEN HISTREC = 53 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9950_9969_CHRONIC_MYELOPROLIFERATIVE_DISORDERS_C421,
    CASE
        WHEN HISTREC = 54 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9970_9979_OTHER_HEMATOLOGIC_DISORDERS,
    CASE
        WHEN HISTREC = 55 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_9980_9989_MYELODYSPLASTIC_SYNDROME,
    CASE
        WHEN HISTRECB = 01 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_BRAIN_DIFFUSE_ASTROCYTOMA_PROTOPLASMA_FIBRILLARY,
    CASE
        WHEN HISTRECB = 02 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_BRAIN_ANAPLASTIC_ASTROCYTOMA,
    CASE
        WHEN HISTRECB = 03 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_BRAIN_GLIOBLASTOMA,
    CASE
        WHEN HISTRECB = 04 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_BRAIN_PILOCYTIC_ASTROCYTOMA,
    CASE
        WHEN HISTRECB = 05 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_BRAIN_UNIQUE_ASTROCYTOMA_VARIANTS,
    CASE
        WHEN HISTRECB = 06 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_BRAIN_OLIGODENDROGLIOMA,
    CASE
        WHEN HISTRECB = 07 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_BRAIN_ANAPLASTIC_OLIGODENDROGLIOMA,
    CASE
        WHEN HISTRECB = 08 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_BRAIN_EPENDYMOMA_ANAPLASTIC_EPENDYMOMA,
    CASE
        WHEN HISTRECB = 09 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_BRAIN_EPENDYMOMA_VARIANTS,
    CASE
        WHEN HISTRECB = 10 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_BRAIN_MIXED_GLIOMA,
    CASE
        WHEN HISTRECB = 11 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_BRAIN_ASTROCYTOMA,
    CASE
        WHEN HISTRECB = 12 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_BRAIN_GLIOMA,
    CASE
        WHEN HISTRECB = 13 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_BRAIN_CHOROID_PLEXUS,
    CASE
        WHEN HISTRECB = 14 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_BRAIN_NEUROEPITHELIAL,
    CASE
        WHEN HISTRECB = 15 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_BRAIN_BENIGN_AND_MALIGNANT_NEURONAL_GLIAL,
    CASE
        WHEN HISTRECB = 16 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_BRAIN_PINEAL_PARENCHYMAL,
    CASE
        WHEN HISTRECB = 17 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_BRAIN_EMBRYONAL_PRIMITIVE_MEDULLOBLASTOMA,
    CASE
        WHEN HISTRECB = 18 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_BRAIN_NERVE_SHEATH_BENIGN_AND_MALIGNANT,
    CASE
        WHEN HISTRECB = 19 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_BRAIN_MENINGIOMA_BENIGN_AND_MALIGNANT,
    CASE
        WHEN HISTRECB = 20 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_BRAIN_OTHER_MESENCHYMAL_BENIGN_AND_MALIGNANT,
    CASE
        WHEN HISTRECB = 21 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_BRAIN_HEMANGIOMA_AND_HEMAGIOBLASTOMA,
    CASE
        WHEN HISTRECB = 22 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_BRAIN_LYMPHOMA,
    CASE
        WHEN HISTRECB = 23 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_BRAIN_GERM_CELL_TUMORS_CYSTS_AND_HETEROTOPIAS,
    CASE
        WHEN HISTRECB = 24 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_BRAIN_CHORDOMA_CHONDROSARCOMA,
    CASE
        WHEN HISTRECB = 25 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_BRAIN_PITUITARY,
    CASE
        WHEN HISTRECB = 26 THEN 1 ELSE 0
    END AS HISTOLOGY_GROUP_BRAIN_CRANIOPHARYNGIOMA,
    CASE WHEN RAC_RECA = 1 THEN 1 ELSE 0 END AS RACE_WHITE,
    CASE WHEN RAC_RECA = 2 THEN 1 ELSE 0 END AS RACE_BLACK,
    CASE WHEN RAC_RECA IN (3, 7) THEN 1 ELSE 0 END AS RACE_OTHER,
    CASE WHEN SUBSTRING(ST_CNTY, 2) = 01 THEN 1 ELSE 0 END AS STATE_ALABAMA,
    CASE WHEN SUBSTRING(ST_CNTY, 2) = 02 THEN 1 ELSE 0 END AS STATE_ALASKA,
    CASE WHEN SUBSTRING(ST_CNTY, 2) = 04 THEN 1 ELSE 0 END AS STATE_ARIZONA,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 05 THEN 1 ELSE 0
    END AS STATE_ARKANSAS,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 06 THEN 1 ELSE 0
    END AS STATE_CALIFORNIA,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 08 THEN 1 ELSE 0
    END AS STATE_COLORADO,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 09 THEN 1 ELSE 0
    END AS STATE_CONNECTICUT,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 10 THEN 1 ELSE 0
    END AS STATE_DELAWARE,
    CASE WHEN SUBSTRING(ST_CNTY, 2) = 12 THEN 1 ELSE 0 END AS STATE_FLORIDA,
    CASE WHEN SUBSTRING(ST_CNTY, 2) = 13 THEN 1 ELSE 0 END AS STATE_GEORGIA,
    CASE WHEN SUBSTRING(ST_CNTY, 2) = 15 THEN 1 ELSE 0 END AS STATE_HAWAII,
    CASE WHEN SUBSTRING(ST_CNTY, 2) = 16 THEN 1 ELSE 0 END AS STATE_IDAHO,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 17 THEN 1 ELSE 0
    END AS STATE_ILLINOIS,
    CASE WHEN SUBSTRING(ST_CNTY, 2) = 18 THEN 1 ELSE 0 END AS STATE_INDIANA,
    CASE WHEN SUBSTRING(ST_CNTY, 2) = 19 THEN 1 ELSE 0 END AS STATE_IOWA,
    CASE WHEN SUBSTRING(ST_CNTY, 2) = 20 THEN 1 ELSE 0 END AS STATE_KANSAS,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 21 THEN 1 ELSE 0
    END AS STATE_KENTUCKY,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 22 THEN 1 ELSE 0
    END AS STATE_LOUISIANA,
    CASE WHEN SUBSTRING(ST_CNTY, 2) = 23 THEN 1 ELSE 0 END AS STATE_MAINE,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 24 THEN 1 ELSE 0
    END AS STATE_MARYLAND,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 25 THEN 1 ELSE 0
    END AS STATE_MASSACHUSETTS,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 26 THEN 1 ELSE 0
    END AS STATE_MICHIGAN,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 27 THEN 1 ELSE 0
    END AS STATE_MINNESOTA,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 28 THEN 1 ELSE 0
    END AS STATE_MISSISSIPPI,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 29 THEN 1 ELSE 0
    END AS STATE_MISSOURI,
    CASE WHEN SUBSTRING(ST_CNTY, 2) = 30 THEN 1 ELSE 0 END AS STATE_MONTANA,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 31 THEN 1 ELSE 0
    END AS STATE_NEBRASKA,
    CASE WHEN SUBSTRING(ST_CNTY, 2) = 32 THEN 1 ELSE 0 END AS STATE_NEVADA,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 33 THEN 1 ELSE 0
    END AS STATE_NEW_HAMPSHIRE,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 34 THEN 1 ELSE 0
    END AS STATE_NEW_JERSEY,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 35 THEN 1 ELSE 0
    END AS STATE_NEW_MEXICO,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 36 THEN 1 ELSE 0
    END AS STATE_NEW_YORK,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 37 THEN 1 ELSE 0
    END AS STATE_NORTH_CAROLINA,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 38 THEN 1 ELSE 0
    END AS STATE_NORTH_DAKOTA,
    CASE WHEN SUBSTRING(ST_CNTY, 2) = 39 THEN 1 ELSE 0 END AS STATE_OHIO,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 40 THEN 1 ELSE 0
    END AS STATE_OKLAHOMA,
    CASE WHEN SUBSTRING(ST_CNTY, 2) = 41 THEN 1 ELSE 0 END AS STATE_OREGON,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 42 THEN 1 ELSE 0
    END AS STATE_PENNSYLVANIA,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 44 THEN 1 ELSE 0
    END AS STATE_RHODE_ISLAND,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 45 THEN 1 ELSE 0
    END AS STATE_SOUTH_CAROLINA,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 46 THEN 1 ELSE 0
    END AS STATE_SOUTH_DAKOTA,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 47 THEN 1 ELSE 0
    END AS STATE_TENNESSEE,
    CASE WHEN SUBSTRING(ST_CNTY, 2) = 48 THEN 1 ELSE 0 END AS STATE_TEXAS,
    CASE WHEN SUBSTRING(ST_CNTY, 2) = 49 THEN 1 ELSE 0 END AS STATE_UTAH,
    CASE WHEN SUBSTRING(ST_CNTY, 2) = 50 THEN 1 ELSE 0 END AS STATE_VERMONT,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 51 THEN 1 ELSE 0
    END AS STATE_VIRGINIA,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 53 THEN 1 ELSE 0
    END AS STATE_WASHINGTON,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 54 THEN 1 ELSE 0
    END AS STATE_WEST_VIRGINIA,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 55 THEN 1 ELSE 0
    END AS STATE_WISCONSIN,
    CASE WHEN SUBSTRING(ST_CNTY, 2) = 56 THEN 1 ELSE 0 END AS STATE_WYOMING,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 60 THEN 1 ELSE 0
    END AS STATE_AMERICAN_SAMOA,
    CASE WHEN SUBSTRING(ST_CNTY, 2) = 66 THEN 1 ELSE 0 END AS STATE_GUAM,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 69 THEN 1 ELSE 0
    END AS STATE_NORTHERN_MARIANA_ISLANDS,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 72 THEN 1 ELSE 0
    END AS STATE_PUERTO_RICO,
    CASE
        WHEN SUBSTRING(ST_CNTY, 2) = 78 THEN 1 ELSE 0
    END AS STATE_VIRGIN_ISLANDS,
    CASE WHEN VSRTSADX IN (1, 8) THEN 1 ELSE 0 END AS DEAD_DUE_CANCER,
    CASE WHEN ERSTATUS = 1 THEN 1 ELSE 0 END AS BREAST_ER_POSITIVE,
    CASE WHEN ERSTATUS = 2 THEN 1 ELSE 0 END AS BREAST_ER_NEGATIVE,
    CASE WHEN ERSTATUS = 3 THEN 1 ELSE 0 END AS BREAST_ER_BODERLINE,
    CASE WHEN PRSTATUS = 1 THEN 1 ELSE 0 END AS BREAST_PR_POSITIVE,
    CASE WHEN PRSTATUS = 2 THEN 1 ELSE 0 END AS BREAST_PR_NEGATIVE,
    CASE WHEN PRSTATUS = 3 THEN 1 ELSE 0 END AS BREAST_PR_BODERLINE,
    CASE WHEN VASINV = 1 THEN 1 ELSE 0 END AS LYMPH_VASCULAR_INVASION,
    CASE WHEN SRV_TIME_MON != 9999 THEN SRV_TIME_MON END AS TIME_SURVIVAL,
    CASE
        WHEN SRV_TIME_MON != 9999 AND SRV_TIME_MON < 60 THEN 1 ELSE 0
    END AS NO_REMISSION,
    CASE WHEN INSREC_PUB = 1 THEN 1 ELSE 0 END AS INSURANCE_UNINSURED,
    CASE WHEN INSREC_PUB = 2 THEN 1 ELSE 0 END AS INSURANCE_MEDICAID,
    CASE WHEN INSREC_PUB IN (3, 4) THEN 1 ELSE 0 END AS INSURANCE_INSURED,
    CASE WHEN HER2 = 1 THEN 1 ELSE 0 END AS BREAST_HER2_POSITIVE,
    CASE WHEN HER2 = 2 THEN 1 ELSE 0 END AS BREAST_HER2_NEGATIVE,
    CASE WHEN HER2 = 3 THEN 1 ELSE 0 END AS BREAST_HER2_BORDERLINE,
    CASE
        WHEN BRST_SUB = 1 THEN 1 ELSE 0
    END AS BREAST_SUBTYPE_HER2_POSITIVE_HR_POSITIVE,
    CASE
        WHEN BRST_SUB = 2 THEN 1 ELSE 0
    END AS BREAST_SUBTYPE_HER2_POSITIVE_HR_NEGATIVE,
    CASE
        WHEN BRST_SUB = 3 THEN 1 ELSE 0
    END AS BREAST_SUBTYPE_HER2_NEGATIVE_HR_POSITIVE,
    CASE
        WHEN BRST_SUB = 4 THEN 1 ELSE 0
    END AS BREAST_SUBTYPE_HER2_TRIPLE_NEGATIVE,
    CASE WHEN SCMETSDXB_PUB = 0 THEN 1 ELSE 0 END AS METASTASES_BONE_NO,
    CASE WHEN SCMETSDXB_PUB = 1 THEN 1 ELSE 0 END AS METASTASES_BONE,
    CASE WHEN SCMETSDXBR_PUB = 0 THEN 1 ELSE 0 END AS METASTASES_BRAIN_NO,
    CASE WHEN SCMETSDXBR_PUB = 1 THEN 1 ELSE 0 END AS METASTASES_BRAIN,
    CASE WHEN SCMETSDXLIV_PUB = 0 THEN 1 ELSE 0 END AS METASTASES_LIVER_NO,
    CASE WHEN SCMETSDXLIV_PUB = 1 THEN 1 ELSE 0 END AS METASTASES_LIVER,
    CASE WHEN SCMETSDXLUNG_PUB = 0 THEN 1 ELSE 0 END AS METASTASES_LUNG_NO,
    CASE WHEN SCMETSDXLUNG_PUB = 1 THEN 1 ELSE 0 END AS METASTASES_LUNG,
    CASE
        WHEN METSDXLN = 0 THEN 1 ELSE 0
    END AS METASTASES_DISTANT_LYMPH_NODE_NO,
    CASE
        WHEN METSDXLN = 1 THEN 1 ELSE 0
    END AS METASTASES_DISTANT_LYMPH_NODE,
    CASE WHEN METSDXO = 0 THEN 1 ELSE 0 END AS METASTASES_OTHER_NO,
    CASE WHEN METSDXO = 1 THEN 1 ELSE 0 END AS METASTASES_OTHER,
    CASE WHEN RADIATNR = 1 THEN 1 ELSE 0 END AS RADIATION_BEAM,
    CASE
        WHEN RADIATNR = 2 THEN 1 ELSE 0
    END AS RADIATION_RADIOACTIVE_IMPLANTS,
    CASE WHEN RADIATNR = 3 THEN 1 ELSE 0 END AS RADIATION_RADIOISOTOPES,
    CASE
        WHEN RADIATNR = 4 THEN 1 ELSE 0
    END AS RADIATION_COMB_BEAM_WITH_RADIAC_IMP_OR_RADIOISOTOPES,
    CASE
        WHEN RADIATNR IN (5, 6) THEN 1 ELSE 0
    END AS RADIATION_NOT_SPECIFIED,
    CASE WHEN RADIATNR = 7 THEN 1 ELSE 0 END AS RADIATION_REFUSED,
    CASE WHEN RAD_SURG = 0 THEN 1 ELSE 0 END AS RADIATION_SEQUENCE_NOT_USED,
    CASE
        WHEN RAD_SURG = 2 THEN 1 ELSE 0
    END AS RADIATION_SEQUENCE_RAD_BEFORE_SUR,
    CASE
        WHEN RAD_SURG = 3 THEN 1 ELSE 0
    END AS RADIATION_SEQUENCE_RAD_AFTER_SUR,
    CASE
        WHEN RAD_SURG = 4 THEN 1 ELSE 0
    END AS RADIATION_SEQUENCE_RAD_BOTH_BEFORE_AFTER_SUR,
    CASE
        WHEN RAD_SURG = 5 THEN 1 ELSE 0
    END AS RADIATION_SEQUENCE_INTRAOPERATIVE_RADIATION,
    CASE
        WHEN RAD_SURG = 6 THEN 1 ELSE 0
    END AS RADIATION_SEQUENCE_INTRAOPERATIVE_RADIATION_WITH_OTHER_RAD,
    CASE
        WHEN RAD_SURG = 7 THEN 1 ELSE 0
    END AS RADIATION_SEQUENCE_SUR_BOTH_BEFORE_AFTER_RAD
FROM PRE_PROCESSING_1
WHERE SRV_TIME_MON != 9999 --119877
